"""Canonical schema for the versioned weather observation tables.

These tables (added 2026-04-21) hold multi-NWP, multi-zone, multi-lead
weather data with snapshot versioning via `fetched_at`. They live next
to the existing `weather_data` table (which stays as-is for dashboards).

Schema owner: `able` repo. External consumers (e.g. heliocast) should
import column names and dimension constants from here to stay in sync.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# Weather variable column list (canonical order for INSERT statements)
# ---------------------------------------------------------------------------

# Units in column names mirror `weather_data` (able's existing convention):
# _wm2 = W/m², _k = Kelvin, _c = Celsius, _frac = 0–1, _hpa = hPa,
# _ms = m/s, _deg = degrees, _mm = millimetres, _s = seconds.
#
# Open-Meteo returns most radiation + temp + wind values already in these
# units (or degrees C for temperature). Ingestors convert where needed.

WEATHER_VARIABLE_COLUMNS = [
    # Radiation — accumulated (period-averaged, W/m²)
    "shortwave_radiation_wm2",
    "direct_radiation_wm2",
    "direct_normal_irradiance_wm2",
    "diffuse_radiation_wm2",
    "global_tilted_irradiance_wm2",
    "terrestrial_radiation_wm2",
    # Radiation — instantaneous
    "shortwave_radiation_instant_wm2",
    "direct_radiation_instant_wm2",
    "direct_normal_irradiance_instant_wm2",
    "diffuse_radiation_instant_wm2",
    "global_tilted_irradiance_instant_wm2",
    "terrestrial_radiation_instant_wm2",
    # Cloud
    "cloud_cover_frac",
    "cloud_cover_low_frac",
    "cloud_cover_mid_frac",
    "cloud_cover_high_frac",
    "sunshine_duration_s",
    # Thermodynamic
    "temperature_2m_c",
    "dew_point_2m_c",
    "relative_humidity_2m_frac",
    "pressure_msl_hpa",
    # Wind
    "wind_speed_10m_ms",
    "wind_direction_10m_deg",
    "wind_gusts_10m_ms",
    "wind_speed_100m_ms",
    # Precipitation
    "precip_mm",
    "rain_mm",
    "snowfall_mm",
]


# ---------------------------------------------------------------------------
# Mapping from Open-Meteo API field names → our suffixed column names
# ---------------------------------------------------------------------------
#
# Ingestors use this to translate raw API responses into DB-ready rows.
# Keys are Open-Meteo hourly variable names; values are our DB columns.

OPENMETEO_TO_DB = {
    "shortwave_radiation": "shortwave_radiation_wm2",
    "direct_radiation": "direct_radiation_wm2",
    "direct_normal_irradiance": "direct_normal_irradiance_wm2",
    "diffuse_radiation": "diffuse_radiation_wm2",
    "global_tilted_irradiance": "global_tilted_irradiance_wm2",
    "terrestrial_radiation": "terrestrial_radiation_wm2",
    "shortwave_radiation_instant": "shortwave_radiation_instant_wm2",
    "direct_radiation_instant": "direct_radiation_instant_wm2",
    "direct_normal_irradiance_instant": "direct_normal_irradiance_instant_wm2",
    "diffuse_radiation_instant": "diffuse_radiation_instant_wm2",
    "global_tilted_irradiance_instant": "global_tilted_irradiance_instant_wm2",
    "terrestrial_radiation_instant": "terrestrial_radiation_instant_wm2",
    "cloud_cover": "cloud_cover_frac",
    "cloud_cover_low": "cloud_cover_low_frac",
    "cloud_cover_mid": "cloud_cover_mid_frac",
    "cloud_cover_high": "cloud_cover_high_frac",
    "sunshine_duration": "sunshine_duration_s",
    "temperature_2m": "temperature_2m_c",
    "dew_point_2m": "dew_point_2m_c",
    "relative_humidity_2m": "relative_humidity_2m_frac",
    "pressure_msl": "pressure_msl_hpa",
    "wind_speed_10m": "wind_speed_10m_ms",
    "wind_direction_10m": "wind_direction_10m_deg",
    "wind_gusts_10m": "wind_gusts_10m_ms",
    "wind_speed_100m": "wind_speed_100m_ms",
    "precipitation": "precip_mm",
    "rain": "rain_mm",
    "snowfall": "snowfall_mm",
}


# ---------------------------------------------------------------------------
# Dimension seeds — unified locations source of truth
# ---------------------------------------------------------------------------
#
# Tuple shape: (country_code, zone_id, zone_type, lat, lon, weight, capacity_mw, description)
#
# zone_type values:
#   'centroid'      — single-point country centroid (legacy weather_data semantics)
#   'solar'         — capacity-weighted PV cluster
#   'wind_onshore'  — capacity-weighted onshore wind cluster
#   'wind_offshore' — capacity-weighted offshore wind cluster
#
# The LOCATIONS block between the AUTOGEN markers is regenerated by
# `scripts/build_weather_locations.py` from GEM (Global Energy Monitor)
# plant-level data. Edit via a rebuild, not by hand — hand edits will
# be clobbered on the next build. The BE centroid row is hand-seeded
# (no GEM centroid row type) and is preserved across rebuilds.

# === LOCATIONS-AUTOGEN-START === (generated by scripts/build_weather_locations.py — do not edit by hand) ===
LOCATIONS = [
    # country, zone_id, zone_type, lat, lon, weight, capacity_mw, description
    ('AL' , 'centroid'              , 'centroid'    ,  41.000,  20.000,  1.000,    None, 'Albania centroid'),
    ('AL' , 'solar_country'         , 'solar'       ,  40.808,  19.711,  1.000,   354.2, 'Albania solar cluster, 354 MW across 22 plants (radius 148 km)'),
    ('AT' , 'centroid'              , 'centroid'    ,  47.700,  13.350,  1.000,    None, 'Austria centroid'),
    ('AT' , 'solar_1'               , 'solar'       ,  47.887,  16.437,  0.598,   513.1, 'Austria solar cluster, 513 MW across 98 plants (radius 140 km)'),
    ('AT' , 'solar_2'               , 'solar'       ,  47.530,  14.565,  0.402,   345.3, 'Austria solar cluster, 345 MW across 116 plants (radius 213 km)'),
    ('AT' , 'wind_onshore_1'        , 'wind_onshore',  47.956,  16.879,  0.536,  1655.0, 'Austria wind_onshore cluster, 1655 MW across 59 plants (radius 47 km)'),
    ('AT' , 'wind_onshore_2'        , 'wind_onshore',  48.468,  16.668,  0.330,  1019.0, 'Austria wind_onshore cluster, 1019 MW across 50 plants (radius 88 km)'),
    ('AT' , 'wind_onshore_3'        , 'wind_onshore',  47.661,  15.280,  0.135,   416.0, 'Austria wind_onshore cluster, 416 MW across 20 plants (radius 159 km)'),
    ('BA' , 'centroid'              , 'centroid'    ,  43.900,  17.700,  1.000,    None, 'Bosnia and Herzegovina centroid'),
    ('BA' , 'solar_country'         , 'solar'       ,  43.453,  17.843,  1.000,   539.5, 'Bosnia and Herzegovina solar cluster, 540 MW across 75 plants (radius 199 km)'),
    ('BA' , 'wind_onshore_country'  , 'wind_onshore',  43.664,  17.420,  1.000,   244.0, 'Bosnia and Herzegovina wind_onshore cluster, 244 MW across 5 plants (radius 76 km)'),
    ('BE' , 'centroid'              , 'centroid'    ,  50.500,   4.450,  1.000,    None, 'Belgium centroid'),
    ('BE' , 'solar_1'               , 'solar'       ,  50.975,   3.865,  0.668,   604.4, 'Belgium solar cluster, 604 MW across 141 plants (radius 83 km)'),
    ('BE' , 'solar_2'               , 'solar'       ,  50.764,   5.107,  0.332,   300.7, 'Belgium solar cluster, 301 MW across 79 plants (radius 137 km)'),
    ('BE' , 'wind_onshore_1'        , 'wind_onshore',  50.815,   3.953,  0.536,   916.0, 'Belgium wind_onshore cluster, 916 MW across 48 plants (radius 91 km)'),
    ('BE' , 'wind_onshore_2'        , 'wind_onshore',  50.671,   5.233,  0.464,   794.0, 'Belgium wind_onshore cluster, 794 MW across 53 plants (radius 96 km)'),
    ('BE' , 'wind_offshore_country' , 'wind_offshore',  51.613,   2.888,  1.000,  2256.0, 'Belgium wind_offshore cluster, 2256 MW across 11 plants (radius 16 km)'),
    ('BG' , 'centroid'              , 'centroid'    ,  42.700,  25.500,  1.000,    None, 'Bulgaria centroid'),
    ('BG' , 'solar_1'               , 'solar'       ,  42.594,  25.944,  0.367,  1294.6, 'Bulgaria solar cluster, 1295 MW across 160 plants (radius 128 km)'),
    ('BG' , 'solar_2'               , 'solar'       ,  42.390,  24.702,  0.300,  1060.4, 'Bulgaria solar cluster, 1060 MW across 92 plants (radius 120 km)'),
    ('BG' , 'solar_3'               , 'solar'       ,  43.285,  27.184,  0.121,   426.1, 'Bulgaria solar cluster, 426 MW across 84 plants (radius 134 km)'),
    ('BG' , 'solar_4'               , 'solar'       ,  43.520,  23.891,  0.115,   404.8, 'Bulgaria solar cluster, 405 MW across 61 plants (radius 120 km)'),
    ('BG' , 'solar_5'               , 'solar'       ,  42.183,  23.352,  0.097,   343.1, 'Bulgaria solar cluster, 343 MW across 45 plants (radius 88 km)'),
    ('BG' , 'wind_onshore_country'  , 'wind_onshore',  43.354,  27.884,  1.000,   608.0, 'Bulgaria wind_onshore cluster, 608 MW across 20 plants (radius 211 km)'),
    ('CH' , 'centroid'              , 'centroid'    ,  46.800,   8.200,  1.000,    None, 'Switzerland centroid'),
    ('CH' , 'solar_country'         , 'solar'       ,  46.999,   7.671,  1.000,    96.7, 'Switzerland solar cluster, 97 MW across 53 plants (radius 156 km)'),
    ('CH' , 'wind_onshore_country'  , 'wind_onshore',  46.944,   7.218,  1.000,    55.0, 'Switzerland wind_onshore cluster, 55 MW across 4 plants (radius 113 km)'),
    ('CY' , 'centroid'              , 'centroid'    ,  35.000,  33.000,  1.000,    None, 'Cyprus centroid'),
    ('CY' , 'solar_country'         , 'solar'       ,  35.007,  33.322,  1.000,   395.9, 'Cyprus solar cluster, 396 MW across 105 plants (radius 85 km)'),
    ('CY' , 'wind_onshore_country'  , 'wind_onshore',  34.825,  33.060,  1.000,   156.0, 'Cyprus wind_onshore cluster, 156 MW across 5 plants (radius 44 km)'),
    ('CZ' , 'centroid'              , 'centroid'    ,  49.850,  15.500,  1.000,    None, 'Czechia centroid'),
    ('CZ' , 'solar_1'               , 'solar'       ,  49.899,  14.129,  0.506,  1424.6, 'Czechia solar cluster, 1425 MW across 373 plants (radius 139 km)'),
    ('CZ' , 'solar_2'               , 'solar'       ,  49.307,  16.771,  0.494,  1389.2, 'Czechia solar cluster, 1389 MW across 360 plants (radius 142 km)'),
    ('CZ' , 'wind_onshore_country'  , 'wind_onshore',  50.136,  14.470,  1.000,   151.0, 'Czechia wind_onshore cluster, 151 MW across 8 plants (radius 215 km)'),
    ('DE' , 'centroid'              , 'centroid'    ,  51.200,  10.450,  1.000,    None, 'Germany centroid'),
    ('DE' , 'solar_1'               , 'solar'       ,  52.002,  14.070,  0.108,  4095.7, 'Germany solar cluster, 4096 MW across 555 plants (radius 140 km)'),
    ('DE' , 'solar_2'               , 'solar'       ,  51.349,  12.536,  0.095,  3623.9, 'Germany solar cluster, 3624 MW across 712 plants (radius 113 km)'),
    ('DE' , 'solar_3'               , 'solar'       ,  49.825,  10.298,  0.088,  3358.9, 'Germany solar cluster, 3359 MW across 646 plants (radius 121 km)'),
    ('DE' , 'solar_4'               , 'solar'       ,  53.120,  12.047,  0.085,  3222.5, 'Germany solar cluster, 3222 MW across 446 plants (radius 128 km)'),
    ('DE' , 'solar_5'               , 'solar'       ,  48.444,  10.836,  0.084,  3209.6, 'Germany solar cluster, 3210 MW across 730 plants (radius 107 km)'),
    ('DE' , 'solar_6'               , 'solar'       ,  49.635,  11.684,  0.083,  3143.0, 'Germany solar cluster, 3143 MW across 589 plants (radius 119 km)'),
    ('DE' , 'solar_7'               , 'solar'       ,  48.657,  12.574,  0.074,  2826.9, 'Germany solar cluster, 2827 MW across 838 plants (radius 105 km)'),
    ('DE' , 'solar_8'               , 'solar'       ,  53.554,  13.370,  0.065,  2467.3, 'Germany solar cluster, 2467 MW across 357 plants (radius 116 km)'),
    ('DE' , 'solar_9'               , 'solar'       ,  51.806,  11.144,  0.060,  2264.8, 'Germany solar cluster, 2265 MW across 596 plants (radius 138 km)'),
    ('DE' , 'solar_10'              , 'solar'       ,  49.842,   7.085,  0.057,  2184.4, 'Germany solar cluster, 2184 MW across 472 plants (radius 110 km)'),
    ('DE' , 'solar_11'              , 'solar'       ,  54.190,   9.579,  0.057,  2169.4, 'Germany solar cluster, 2169 MW across 348 plants (radius 168 km)'),
    ('DE' , 'solar_12'              , 'solar'       ,  48.632,   9.004,  0.050,  1897.7, 'Germany solar cluster, 1898 MW across 506 plants (radius 154 km)'),
    ('DE' , 'solar_13'              , 'solar'       ,  51.177,   9.320,  0.038,  1431.2, 'Germany solar cluster, 1431 MW across 397 plants (radius 162 km)'),
    ('DE' , 'solar_14'              , 'solar'       ,  52.910,   8.250,  0.028,  1066.4, 'Germany solar cluster, 1066 MW across 304 plants (radius 129 km)'),
    ('DE' , 'solar_15'              , 'solar'       ,  51.267,   6.901,  0.028,  1064.4, 'Germany solar cluster, 1064 MW across 329 plants (radius 151 km)'),
    ('DE' , 'wind_onshore_1'        , 'wind_onshore',  54.368,   9.180,  0.116,  4806.7, 'Germany wind_onshore cluster, 4807 MW across 249 plants (radius 80 km)'),
    ('DE' , 'wind_onshore_2'        , 'wind_onshore',  51.465,  11.481,  0.101,  4171.3, 'Germany wind_onshore cluster, 4171 MW across 212 plants (radius 164 km)'),
    ('DE' , 'wind_onshore_3'        , 'wind_onshore',  53.102,  11.939,  0.091,  3785.0, 'Germany wind_onshore cluster, 3785 MW across 188 plants (radius 129 km)'),
    ('DE' , 'wind_onshore_4'        , 'wind_onshore',  53.116,   8.939,  0.082,  3399.4, 'Germany wind_onshore cluster, 3399 MW across 171 plants (radius 90 km)'),
    ('DE' , 'wind_onshore_5'        , 'wind_onshore',  51.148,   9.063,  0.067,  2782.5, 'Germany wind_onshore cluster, 2782 MW across 147 plants (radius 114 km)'),
    ('DE' , 'wind_onshore_6'        , 'wind_onshore',  49.694,   7.768,  0.065,  2695.8, 'Germany wind_onshore cluster, 2696 MW across 156 plants (radius 225 km)'),
    ('DE' , 'wind_onshore_7'        , 'wind_onshore',  53.259,   7.512,  0.063,  2620.8, 'Germany wind_onshore cluster, 2621 MW across 116 plants (radius 69 km)'),
    ('DE' , 'wind_onshore_8'        , 'wind_onshore',  53.464,  13.711,  0.061,  2529.5, 'Germany wind_onshore cluster, 2530 MW across 121 plants (radius 115 km)'),
    ('DE' , 'wind_onshore_9'        , 'wind_onshore',  51.988,  14.120,  0.060,  2491.8, 'Germany wind_onshore cluster, 2492 MW across 117 plants (radius 127 km)'),
    ('DE' , 'wind_onshore_10'       , 'wind_onshore',  52.443,  10.438,  0.057,  2383.5, 'Germany wind_onshore cluster, 2384 MW across 114 plants (radius 113 km)'),
    ('DE' , 'wind_onshore_11'       , 'wind_onshore',  51.858,  13.008,  0.057,  2377.5, 'Germany wind_onshore cluster, 2378 MW across 127 plants (radius 126 km)'),
    ('DE' , 'wind_onshore_12'       , 'wind_onshore',  52.230,   7.482,  0.053,  2189.6, 'Germany wind_onshore cluster, 2190 MW across 120 plants (radius 105 km)'),
    ('DE' , 'wind_onshore_13'       , 'wind_onshore',  49.325,  10.311,  0.050,  2068.5, 'Germany wind_onshore cluster, 2068 MW across 125 plants (radius 186 km)'),
    ('DE' , 'wind_onshore_14'       , 'wind_onshore',  50.654,   6.421,  0.042,  1742.5, 'Germany wind_onshore cluster, 1742 MW across 94 plants (radius 130 km)'),
    ('DE' , 'wind_onshore_15'       , 'wind_onshore',  53.972,  10.674,  0.035,  1465.8, 'Germany wind_onshore cluster, 1466 MW across 69 plants (radius 88 km)'),
    ('DE' , 'wind_offshore_1'       , 'wind_offshore',  54.498,   7.729,  0.221,  1995.0, 'Germany wind_offshore cluster, 1995 MW across 7 plants (radius 94 km)'),
    ('DE' , 'wind_offshore_2'       , 'wind_offshore',  53.990,   6.518,  0.192,  1734.0, 'Germany wind_offshore cluster, 1734 MW across 8 plants (radius 33 km)'),
    ('DE' , 'wind_offshore_3'       , 'wind_offshore',  54.823,  13.919,  0.163,  1467.0, 'Germany wind_offshore cluster, 1467 MW across 4 plants (radius 18 km)'),
    ('DE' , 'wind_offshore_4'       , 'wind_offshore',  54.330,   5.888,  0.118,  1062.0, 'Germany wind_offshore cluster, 1062 MW across 3 plants (radius 7 km)'),
    ('DE' , 'wind_offshore_5'       , 'wind_offshore',  54.469,   6.337,  0.112,  1009.0, 'Germany wind_offshore cluster, 1009 MW across 3 plants (radius 4 km)'),
    ('DE' , 'wind_offshore_6'       , 'wind_offshore',  54.040,   7.030,  0.094,   847.0, 'Germany wind_offshore cluster, 847 MW across 3 plants (radius 5 km)'),
    ('DE' , 'wind_offshore_7'       , 'wind_offshore',  55.165,   7.030,  0.064,   576.0, 'Germany wind_offshore cluster, 576 MW across 2 plants (radius 11 km)'),
    ('DE' , 'wind_offshore_8'       , 'wind_offshore',  54.948,  13.123,  0.037,   336.0, 'Germany wind_offshore cluster, 336 MW across 2 plants (radius 45 km)'),
    ('DK' , 'centroid'              , 'centroid'    ,  56.200,  10.000,  1.000,    None, 'Denmark centroid'),
    ('DK' , 'solar_1'               , 'solar'       ,  55.398,   9.160,  0.352,  1190.4, 'Denmark solar cluster, 1190 MW across 60 plants (radius 82 km)'),
    ('DK' , 'solar_2'               , 'solar'       ,  56.375,   8.579,  0.240,   812.8, 'Denmark solar cluster, 813 MW across 45 plants (radius 86 km)'),
    ('DK' , 'solar_3'               , 'solar'       ,  55.023,  10.996,  0.167,   566.3, 'Denmark solar cluster, 566 MW across 33 plants (radius 82 km)'),
    ('DK' , 'solar_4'               , 'solar'       ,  55.248,  12.018,  0.139,   470.5, 'Denmark solar cluster, 470 MW across 42 plants (radius 195 km)'),
    ('DK' , 'solar_5'               , 'solar'       ,  56.841,  10.059,  0.102,   343.9, 'Denmark solar cluster, 344 MW across 50 plants (radius 86 km)'),
    ('DK' , 'wind_onshore_1'        , 'wind_onshore',  56.254,   8.705,  0.608,  1428.6, 'Denmark wind_onshore cluster, 1429 MW across 70 plants (radius 159 km)'),
    ('DK' , 'wind_onshore_2'        , 'wind_onshore',  56.343,  10.437,  0.392,   922.1, 'Denmark wind_onshore cluster, 922 MW across 46 plants (radius 187 km)'),
    ('DK' , 'wind_offshore_1'       , 'wind_offshore',  55.886,   7.856,  0.442,  1171.0, 'Denmark wind_offshore cluster, 1171 MW across 7 plants (radius 91 km)'),
    ('DK' , 'wind_offshore_2'       , 'wind_offshore',  55.039,  12.968,  0.247,   656.0, 'Denmark wind_offshore cluster, 656 MW across 3 plants (radius 75 km)'),
    ('DK' , 'wind_offshore_3'       , 'wind_offshore',  56.569,  11.139,  0.163,   431.6, 'Denmark wind_offshore cluster, 432 MW across 3 plants (radius 103 km)'),
    ('DK' , 'wind_offshore_4'       , 'wind_offshore',  54.569,  11.641,  0.148,   394.0, 'Denmark wind_offshore cluster, 394 MW across 3 plants (radius 97 km)'),
    ('EE' , 'centroid'              , 'centroid'    ,  58.600,  25.000,  1.000,    None, 'Estonia centroid'),
    ('EE' , 'solar_1'               , 'solar'       ,  58.811,  24.337,  0.539,   564.1, 'Estonia solar cluster, 564 MW across 66 plants (radius 117 km)'),
    ('EE' , 'solar_2'               , 'solar'       ,  58.700,  26.414,  0.461,   481.5, 'Estonia solar cluster, 482 MW across 124 plants (radius 124 km)'),
    ('EE' , 'wind_onshore_country'  , 'wind_onshore',  58.968,  25.727,  1.000,   688.0, 'Estonia wind_onshore cluster, 688 MW across 15 plants (radius 139 km)'),
    ('ES' , 'centroid'              , 'centroid'    ,  39.850,  -2.500,  1.000,    None, 'Spain centroid'),
    ('ES' , 'solar_1'               , 'solar'       ,  38.539,  -5.855,  0.573, 20768.6, 'Spain solar cluster, 20769 MW across 1149 plants (radius 1570 km)'),
    ('ES' , 'solar_2'               , 'solar'       ,  39.911,  -1.812,  0.427, 15462.1, 'Spain solar cluster, 15462 MW across 1442 plants (radius 517 km)'),
    ('ES' , 'wind_onshore_1'        , 'wind_onshore',  41.543,  -1.009,  0.157,  4868.3, 'Spain wind_onshore cluster, 4868 MW across 143 plants (radius 95 km)'),
    ('ES' , 'wind_onshore_2'        , 'wind_onshore',  43.088,  -7.145,  0.106,  3291.6, 'Spain wind_onshore cluster, 3292 MW across 126 plants (radius 127 km)'),
    ('ES' , 'wind_onshore_3'        , 'wind_onshore',  39.065,  -1.486,  0.097,  2993.7, 'Spain wind_onshore cluster, 2994 MW across 85 plants (radius 110 km)'),
    ('ES' , 'wind_onshore_4'        , 'wind_onshore',  42.372,  -3.913,  0.094,  2923.7, 'Spain wind_onshore cluster, 2924 MW across 93 plants (radius 143 km)'),
    ('ES' , 'wind_onshore_5'        , 'wind_onshore',  42.271,  -1.830,  0.090,  2775.2, 'Spain wind_onshore cluster, 2775 MW across 99 plants (radius 122 km)'),
    ('ES' , 'wind_onshore_6'        , 'wind_onshore',  36.581,  -5.542,  0.071,  2206.0, 'Spain wind_onshore cluster, 2206 MW across 87 plants (radius 116 km)'),
    ('ES' , 'wind_onshore_7'        , 'wind_onshore',  41.421,  -5.196,  0.064,  1994.5, 'Spain wind_onshore cluster, 1994 MW across 65 plants (radius 181 km)'),
    ('ES' , 'wind_onshore_8'        , 'wind_onshore',  42.813,  -8.538,  0.060,  1867.7, 'Spain wind_onshore cluster, 1868 MW across 70 plants (radius 107 km)'),
    ('ES' , 'wind_onshore_9'        , 'wind_onshore',  39.293,  -2.574,  0.060,  1866.2, 'Spain wind_onshore cluster, 1866 MW across 40 plants (radius 127 km)'),
    ('ES' , 'wind_onshore_10'       , 'wind_onshore',  41.362,  -2.494,  0.058,  1799.2, 'Spain wind_onshore cluster, 1799 MW across 55 plants (radius 113 km)'),
    ('ES' , 'wind_onshore_11'       , 'wind_onshore',  40.370,  -0.634,  0.049,  1516.8, 'Spain wind_onshore cluster, 1517 MW across 44 plants (radius 87 km)'),
    ('ES' , 'wind_onshore_12'       , 'wind_onshore',  41.334,   0.943,  0.037,  1138.0, 'Spain wind_onshore cluster, 1138 MW across 35 plants (radius 68 km)'),
    ('ES' , 'wind_onshore_13'       , 'wind_onshore',  37.225,  -2.877,  0.033,  1016.0, 'Spain wind_onshore cluster, 1016 MW across 38 plants (radius 113 km)'),
    ('ES' , 'wind_onshore_14'       , 'wind_onshore',  37.520,  -7.269,  0.012,   371.0, 'Spain wind_onshore cluster, 371 MW across 12 plants (radius 120 km)'),
    ('ES' , 'wind_onshore_15'       , 'wind_onshore',  28.302, -15.525,  0.012,   359.2, 'Spain wind_onshore cluster, 359 MW across 19 plants (radius 214 km)'),
    ('ES' , 'wind_offshore_country' , 'wind_offshore',  43.465,  -2.880,  1.000,    20.0, 'Spain wind_offshore cluster, 20 MW across 1 plants (radius 0 km)'),
    ('FI' , 'centroid'              , 'centroid'    ,  64.950,  25.350,  1.000,    None, 'Finland centroid'),
    ('FI' , 'solar_country'         , 'solar'       ,  63.568,  24.644,  1.000,   219.4, 'Finland solar cluster, 219 MW across 28 plants (radius 358 km)'),
    ('FI' , 'wind_onshore_1'        , 'wind_onshore',  64.292,  24.387,  0.282,  2396.9, 'Finland wind_onshore cluster, 2397 MW across 39 plants (radius 60 km)'),
    ('FI' , 'wind_onshore_2'        , 'wind_onshore',  62.139,  21.677,  0.213,  1814.5, 'Finland wind_onshore cluster, 1814 MW across 31 plants (radius 200 km)'),
    ('FI' , 'wind_onshore_3'        , 'wind_onshore',  62.816,  22.264,  0.136,  1155.8, 'Finland wind_onshore cluster, 1156 MW across 22 plants (radius 124 km)'),
    ('FI' , 'wind_onshore_4'        , 'wind_onshore',  65.668,  25.348,  0.121,  1029.9, 'Finland wind_onshore cluster, 1030 MW across 26 plants (radius 220 km)'),
    ('FI' , 'wind_onshore_5'        , 'wind_onshore',  63.566,  26.513,  0.096,   817.2, 'Finland wind_onshore cluster, 817 MW across 12 plants (radius 339 km)'),
    ('FI' , 'wind_onshore_6'        , 'wind_onshore',  63.073,  24.662,  0.088,   751.6, 'Finland wind_onshore cluster, 752 MW across 15 plants (radius 160 km)'),
    ('FI' , 'wind_onshore_7'        , 'wind_onshore',  65.511,  28.134,  0.064,   543.5, 'Finland wind_onshore cluster, 544 MW across 9 plants (radius 138 km)'),
    ('FI' , 'wind_offshore_country' , 'wind_offshore',  61.637,  21.396,  1.000,    42.0, 'Finland wind_offshore cluster, 42 MW across 1 plants (radius 0 km)'),
    ('FR' , 'centroid'              , 'centroid'    ,  46.200,   2.250,  1.000,    None, 'France centroid'),
    ('FR' , 'solar_1'               , 'solar'       ,  44.373,  -0.621,  0.171,  2201.5, 'France solar cluster, 2202 MW across 226 plants (radius 140 km)'),
    ('FR' , 'solar_2'               , 'solar'       ,  43.899,   4.705,  0.092,  1182.8, 'France solar cluster, 1183 MW across 296 plants (radius 141 km)'),
    ('FR' , 'solar_3'               , 'solar'       ,  43.801,   5.993,  0.089,  1144.8, 'France solar cluster, 1145 MW across 175 plants (radius 105 km)'),
    ('FR' , 'solar_4'               , 'solar'       ,  43.921,   1.305,  0.077,   994.4, 'France solar cluster, 994 MW across 220 plants (radius 136 km)'),
    ('FR' , 'solar_5'               , 'solar'       ,  46.301,   2.044,  0.075,   963.5, 'France solar cluster, 964 MW across 137 plants (radius 159 km)'),
    ('FR' , 'solar_6'               , 'solar'       ,  43.219,   2.732,  0.070,   900.6, 'France solar cluster, 901 MW across 220 plants (radius 174 km)'),
    ('FR' , 'solar_7'               , 'solar'       ,  45.822,   0.004,  0.065,   837.5, 'France solar cluster, 838 MW across 169 plants (radius 139 km)'),
    ('FR' , 'solar_8'               , 'solar'       ,  47.167,   3.586,  0.064,   828.3, 'France solar cluster, 828 MW across 101 plants (radius 159 km)'),
    ('FR' , 'solar_9'               , 'solar'       ,  48.870,   5.406,  0.059,   763.9, 'France solar cluster, 764 MW across 50 plants (radius 174 km)'),
    ('FR' , 'solar_10'              , 'solar'       ,  47.734,   0.420,  0.048,   620.7, 'France solar cluster, 621 MW across 106 plants (radius 197 km)'),
    ('FR' , 'solar_11'              , 'solar'       ,  45.731,   5.061,  0.045,   582.1, 'France solar cluster, 582 MW across 149 plants (radius 173 km)'),
    ('FR' , 'solar_12'              , 'solar'       ,  48.823,   2.345,  0.044,   563.3, 'France solar cluster, 563 MW across 73 plants (radius 162 km)'),
    ('FR' , 'solar_13'              , 'solar'       ,  48.191,   7.140,  0.039,   498.8, 'France solar cluster, 499 MW across 73 plants (radius 115 km)'),
    ('FR' , 'solar_14'              , 'solar'       ,  49.992,   3.393,  0.035,   447.1, 'France solar cluster, 447 MW across 37 plants (radius 110 km)'),
    ('FR' , 'solar_15'              , 'solar'       ,  47.734,  -1.990,  0.028,   365.4, 'France solar cluster, 365 MW across 93 plants (radius 218 km)'),
    ('FR' , 'wind_onshore_1'        , 'wind_onshore',  48.907,   4.162,  0.155,  3659.8, 'France wind_onshore cluster, 3660 MW across 176 plants (radius 106 km)'),
    ('FR' , 'wind_onshore_2'        , 'wind_onshore',  49.921,   3.164,  0.153,  3622.9, 'France wind_onshore cluster, 3623 MW across 178 plants (radius 108 km)'),
    ('FR' , 'wind_onshore_3'        , 'wind_onshore',  49.928,   1.993,  0.132,  3113.8, 'France wind_onshore cluster, 3114 MW across 195 plants (radius 101 km)'),
    ('FR' , 'wind_onshore_4'        , 'wind_onshore',  46.224,  -0.052,  0.081,  1920.7, 'France wind_onshore cluster, 1921 MW across 121 plants (radius 340 km)'),
    ('FR' , 'wind_onshore_5'        , 'wind_onshore',  43.493,   2.772,  0.081,  1917.8, 'France wind_onshore cluster, 1918 MW across 102 plants (radius 160 km)'),
    ('FR' , 'wind_onshore_6'        , 'wind_onshore',  48.379,   5.316,  0.069,  1634.5, 'France wind_onshore cluster, 1634 MW across 84 plants (radius 125 km)'),
    ('FR' , 'wind_onshore_7'        , 'wind_onshore',  48.235,   1.793,  0.057,  1355.3, 'France wind_onshore cluster, 1355 MW across 79 plants (radius 92 km)'),
    ('FR' , 'wind_onshore_8'        , 'wind_onshore',  46.741,   1.936,  0.047,  1111.7, 'France wind_onshore cluster, 1112 MW across 70 plants (radius 152 km)'),
    ('FR' , 'wind_onshore_9'        , 'wind_onshore',  44.806,   4.140,  0.045,  1062.1, 'France wind_onshore cluster, 1062 MW across 53 plants (radius 193 km)'),
    ('FR' , 'wind_onshore_10'       , 'wind_onshore',  47.403,  -1.316,  0.036,   842.9, 'France wind_onshore cluster, 843 MW across 64 plants (radius 119 km)'),
    ('FR' , 'wind_onshore_11'       , 'wind_onshore',  47.609,   4.069,  0.035,   827.9, 'France wind_onshore cluster, 828 MW across 41 plants (radius 109 km)'),
    ('FR' , 'wind_onshore_12'       , 'wind_onshore',  48.125,  -2.919,  0.035,   821.9, 'France wind_onshore cluster, 822 MW across 54 plants (radius 134 km)'),
    ('FR' , 'wind_onshore_13'       , 'wind_onshore',  48.905,  -0.116,  0.028,   664.1, 'France wind_onshore cluster, 664 MW across 49 plants (radius 149 km)'),
    ('FR' , 'wind_onshore_14'       , 'wind_onshore',  48.958,   6.516,  0.024,   561.6, 'France wind_onshore cluster, 562 MW across 37 plants (radius 93 km)'),
    ('FR' , 'wind_onshore_15'       , 'wind_onshore',  46.917,   6.090,  0.021,   497.7, 'France wind_onshore cluster, 498 MW across 18 plants (radius 507 km)'),
    ('FR' , 'wind_offshore_1'       , 'wind_offshore',  47.636,  -2.511,  0.738,  1472.0, 'France wind_offshore cluster, 1472 MW across 3 plants (radius 128 km)'),
    ('FR' , 'wind_offshore_2'       , 'wind_offshore',  49.526,   0.522,  0.262,   523.0, 'France wind_offshore cluster, 523 MW across 2 plants (radius 785 km)'),
    ('GB' , 'centroid'              , 'centroid'    ,  54.000,  -2.000,  1.000,    None, 'United Kingdom centroid'),
    ('GB' , 'solar_1'               , 'solar'       ,  51.362,  -1.930,  0.307,  3419.1, 'United Kingdom solar cluster, 3419 MW across 377 plants (radius 155 km)'),
    ('GB' , 'solar_2'               , 'solar'       ,  51.976,   0.508,  0.282,  3134.6, 'United Kingdom solar cluster, 3135 MW across 273 plants (radius 164 km)'),
    ('GB' , 'solar_3'               , 'solar'       ,  53.074,  -1.459,  0.220,  2450.5, 'United Kingdom solar cluster, 2450 MW across 312 plants (radius 229 km)'),
    ('GB' , 'solar_4'               , 'solar'       ,  51.027,  -4.172,  0.153,  1706.6, 'United Kingdom solar cluster, 1707 MW across 282 plants (radius 212 km)'),
    ('GB' , 'solar_5'               , 'solar'       ,  54.813,  -4.837,  0.037,   415.4, 'United Kingdom solar cluster, 415 MW across 56 plants (radius 357 km)'),
    ('GB' , 'wind_onshore_1'        , 'wind_onshore',  55.572,  -3.877,  0.242,  3148.7, 'United Kingdom wind_onshore cluster, 3149 MW across 63 plants (radius 102 km)'),
    ('GB' , 'wind_onshore_2'        , 'wind_onshore',  57.373,  -4.619,  0.102,  1329.3, 'United Kingdom wind_onshore cluster, 1329 MW across 27 plants (radius 149 km)'),
    ('GB' , 'wind_onshore_3'        , 'wind_onshore',  55.350,  -4.954,  0.099,  1283.7, 'United Kingdom wind_onshore cluster, 1284 MW across 34 plants (radius 112 km)'),
    ('GB' , 'wind_onshore_4'        , 'wind_onshore',  55.661,  -2.466,  0.093,  1204.8, 'United Kingdom wind_onshore cluster, 1205 MW across 32 plants (radius 108 km)'),
    ('GB' , 'wind_onshore_5'        , 'wind_onshore',  57.176,  -3.205,  0.082,  1066.0, 'United Kingdom wind_onshore cluster, 1066 MW across 28 plants (radius 97 km)'),
    ('GB' , 'wind_onshore_6'        , 'wind_onshore',  51.754,  -3.786,  0.080,  1035.2, 'United Kingdom wind_onshore cluster, 1035 MW across 36 plants (radius 214 km)'),
    ('GB' , 'wind_onshore_7'        , 'wind_onshore',  54.727,  -7.128,  0.077,   996.9, 'United Kingdom wind_onshore cluster, 997 MW across 47 plants (radius 71 km)'),
    ('GB' , 'wind_onshore_8'        , 'wind_onshore',  58.371,  -3.722,  0.056,   723.8, 'United Kingdom wind_onshore cluster, 724 MW across 19 plants (radius 109 km)'),
    ('GB' , 'wind_onshore_9'        , 'wind_onshore',  53.784,  -0.747,  0.050,   648.0, 'United Kingdom wind_onshore cluster, 648 MW across 31 plants (radius 117 km)'),
    ('GB' , 'wind_onshore_10'       , 'wind_onshore',  52.226,  -0.008,  0.049,   630.0, 'United Kingdom wind_onshore cluster, 630 MW across 37 plants (radius 152 km)'),
    ('GB' , 'wind_onshore_11'       , 'wind_onshore',  53.473,  -2.845,  0.038,   492.8, 'United Kingdom wind_onshore cluster, 493 MW across 19 plants (radius 108 km)'),
    ('GB' , 'wind_onshore_12'       , 'wind_onshore',  60.339,  -1.208,  0.034,   443.0, 'United Kingdom wind_onshore cluster, 443 MW across 1 plants (radius 0 km)'),
    ('GB' , 'wind_offshore_1'       , 'wind_offshore',  53.176,   0.702,  0.191,  3042.7, 'United Kingdom wind_offshore cluster, 3043 MW across 10 plants (radius 30 km)'),
    ('GB' , 'wind_offshore_2'       , 'wind_offshore',  53.874,  -3.559,  0.182,  2903.2, 'United Kingdom wind_offshore cluster, 2903 MW across 13 plants (radius 99 km)'),
    ('GB' , 'wind_offshore_3'       , 'wind_offshore',  51.833,   1.789,  0.181,  2885.3, 'United Kingdom wind_offshore cluster, 2885 MW across 11 plants (radius 90 km)'),
    ('GB' , 'wind_offshore_4'       , 'wind_offshore',  53.826,   1.483,  0.159,  2538.0, 'United Kingdom wind_offshore cluster, 2538 MW across 2 plants (radius 17 km)'),
    ('GB' , 'wind_offshore_5'       , 'wind_offshore',  56.532,  -1.844,  0.095,  1513.8, 'United Kingdom wind_offshore cluster, 1514 MW across 8 plants (radius 215 km)'),
    ('GB' , 'wind_offshore_6'       , 'wind_offshore',  58.100,  -3.009,  0.093,  1480.0, 'United Kingdom wind_offshore cluster, 1480 MW across 3 plants (radius 18 km)'),
    ('GB' , 'wind_offshore_7'       , 'wind_offshore',  55.967,   2.330,  0.075,  1200.0, 'United Kingdom wind_offshore cluster, 1200 MW across 1 plants (radius 0 km)'),
    ('GB' , 'wind_offshore_8'       , 'wind_offshore',  50.640,  -0.180,  0.025,   400.0, 'United Kingdom wind_offshore cluster, 400 MW across 1 plants (radius 0 km)'),
    ('GR' , 'centroid'              , 'centroid'    ,  38.250,  24.500,  1.000,    None, 'Greece centroid'),
    ('GR' , 'solar_1'               , 'solar'       ,  40.443,  21.810,  0.236,  1410.5, 'Greece solar cluster, 1410 MW across 354 plants (radius 89 km)'),
    ('GR' , 'solar_2'               , 'solar'       ,  39.326,  22.404,  0.234,  1398.3, 'Greece solar cluster, 1398 MW across 1002 plants (radius 106 km)'),
    ('GR' , 'solar_3'               , 'solar'       ,  40.934,  23.234,  0.201,  1200.6, 'Greece solar cluster, 1201 MW across 834 plants (radius 113 km)'),
    ('GR' , 'solar_4'               , 'solar'       ,  38.721,  21.034,  0.118,   704.4, 'Greece solar cluster, 704 MW across 518 plants (radius 162 km)'),
    ('GR' , 'solar_5'               , 'solar'       ,  38.331,  23.297,  0.089,   534.0, 'Greece solar cluster, 534 MW across 222 plants (radius 96 km)'),
    ('GR' , 'solar_6'               , 'solar'       ,  41.026,  25.398,  0.065,   388.1, 'Greece solar cluster, 388 MW across 333 plants (radius 106 km)'),
    ('GR' , 'solar_7'               , 'solar'       ,  37.171,  22.434,  0.057,   342.3, 'Greece solar cluster, 342 MW across 94 plants (radius 106 km)'),
    ('GR' , 'wind_onshore_1'        , 'wind_onshore',  38.039,  22.793,  0.460,  2165.4, 'Greece wind_onshore cluster, 2165 MW across 95 plants (radius 167 km)'),
    ('GR' , 'wind_onshore_2'        , 'wind_onshore',  37.856,  24.587,  0.232,  1093.2, 'Greece wind_onshore cluster, 1093 MW across 61 plants (radius 357 km)'),
    ('GR' , 'wind_onshore_3'        , 'wind_onshore',  39.818,  21.326,  0.181,   850.0, 'Greece wind_onshore cluster, 850 MW across 29 plants (radius 192 km)'),
    ('GR' , 'wind_onshore_4'        , 'wind_onshore',  41.183,  25.424,  0.127,   597.0, 'Greece wind_onshore cluster, 597 MW across 28 plants (radius 173 km)'),
    ('HR' , 'centroid'              , 'centroid'    ,  44.450,  16.450,  1.000,    None, 'Croatia centroid'),
    ('HR' , 'solar_country'         , 'solar'       ,  45.242,  16.741,  1.000,   271.6, 'Croatia solar cluster, 272 MW across 68 plants (radius 250 km)'),
    ('HR' , 'wind_onshore_1'        , 'wind_onshore',  43.688,  16.513,  0.583,   638.0, 'Croatia wind_onshore cluster, 638 MW across 19 plants (radius 142 km)'),
    ('HR' , 'wind_onshore_2'        , 'wind_onshore',  44.520,  15.273,  0.417,   457.0, 'Croatia wind_onshore cluster, 457 MW across 8 plants (radius 64 km)'),
    ('HU' , 'centroid'              , 'centroid'    ,  47.150,  19.500,  1.000,    None, 'Hungary centroid'),
    ('HU' , 'solar_1'               , 'solar'       ,  47.895,  21.390,  0.319,  1295.7, 'Hungary solar cluster, 1296 MW across 182 plants (radius 130 km)'),
    ('HU' , 'solar_2'               , 'solar'       ,  47.608,  19.321,  0.178,   725.0, 'Hungary solar cluster, 725 MW across 135 plants (radius 89 km)'),
    ('HU' , 'solar_3'               , 'solar'       ,  46.328,  18.309,  0.173,   703.3, 'Hungary solar cluster, 703 MW across 162 plants (radius 114 km)'),
    ('HU' , 'solar_4'               , 'solar'       ,  46.727,  20.166,  0.166,   675.2, 'Hungary solar cluster, 675 MW across 190 plants (radius 105 km)'),
    ('HU' , 'solar_5'               , 'solar'       ,  47.018,  17.271,  0.163,   661.9, 'Hungary solar cluster, 662 MW across 126 plants (radius 106 km)'),
    ('HU' , 'wind_onshore_country'  , 'wind_onshore',  47.557,  17.388,  1.000,   319.0, 'Hungary wind_onshore cluster, 319 MW across 11 plants (radius 56 km)'),
    ('IE' , 'centroid'              , 'centroid'    ,  53.400,  -8.250,  1.000,    None, 'Ireland centroid'),
    ('IE' , 'solar_country'         , 'solar'       ,  52.888,  -6.926,  1.000,   927.1, 'Ireland solar cluster, 927 MW across 35 plants (radius 171 km)'),
    ('IE' , 'wind_onshore_1'        , 'wind_onshore',  52.231,  -9.208,  0.390,  1699.1, 'Ireland wind_onshore cluster, 1699 MW across 58 plants (radius 69 km)'),
    ('IE' , 'wind_onshore_2'        , 'wind_onshore',  53.732,  -9.331,  0.164,   715.0, 'Ireland wind_onshore cluster, 715 MW across 15 plants (radius 62 km)'),
    ('IE' , 'wind_onshore_3'        , 'wind_onshore',  52.913,  -7.916,  0.163,   711.4, 'Ireland wind_onshore cluster, 711 MW across 20 plants (radius 93 km)'),
    ('IE' , 'wind_onshore_4'        , 'wind_onshore',  53.246,  -6.922,  0.155,   677.1, 'Ireland wind_onshore cluster, 677 MW across 21 plants (radius 124 km)'),
    ('IE' , 'wind_onshore_5'        , 'wind_onshore',  54.709,  -7.902,  0.127,   553.5, 'Ireland wind_onshore cluster, 554 MW across 21 plants (radius 89 km)'),
    ('IE' , 'wind_offshore_country' , 'wind_offshore',  52.789,  -5.949,  1.000,    25.0, 'Ireland wind_offshore cluster, 25 MW across 1 plants (radius 0 km)'),
    ('IT' , 'centroid'              , 'centroid'    ,  41.850,  12.550,  1.000,    None, 'Italy centroid'),
    ('IT' , 'solar_1'               , 'solar'       ,  42.417,  11.966,  0.169,   910.9, 'Italy solar cluster, 911 MW across 125 plants (radius 161 km)'),
    ('IT' , 'solar_2'               , 'solar'       ,  41.977,  13.424,  0.133,   719.1, 'Italy solar cluster, 719 MW across 207 plants (radius 168 km)'),
    ('IT' , 'solar_3'               , 'solar'       ,  45.085,  12.230,  0.129,   699.3, 'Italy solar cluster, 699 MW across 145 plants (radius 159 km)'),
    ('IT' , 'solar_4'               , 'solar'       ,  37.471,  13.913,  0.123,   663.8, 'Italy solar cluster, 664 MW across 125 plants (radius 167 km)'),
    ('IT' , 'solar_5'               , 'solar'       ,  41.209,  15.303,  0.118,   638.9, 'Italy solar cluster, 639 MW across 81 plants (radius 98 km)'),
    ('IT' , 'solar_6'               , 'solar'       ,  40.228,  17.278,  0.108,   583.7, 'Italy solar cluster, 584 MW across 97 plants (radius 205 km)'),
    ('IT' , 'solar_7'               , 'solar'       ,  44.993,   8.279,  0.083,   449.7, 'Italy solar cluster, 450 MW across 144 plants (radius 125 km)'),
    ('IT' , 'solar_8'               , 'solar'       ,  40.335,   8.763,  0.079,   427.8, 'Italy solar cluster, 428 MW across 76 plants (radius 128 km)'),
    ('IT' , 'solar_9'               , 'solar'       ,  45.145,  10.376,  0.058,   311.2, 'Italy solar cluster, 311 MW across 140 plants (radius 181 km)'),
    ('IT' , 'wind_onshore_1'        , 'wind_onshore',  41.307,  15.137,  0.386,  4013.5, 'Italy wind_onshore cluster, 4014 MW across 152 plants (radius 152 km)'),
    ('IT' , 'wind_onshore_2'        , 'wind_onshore',  37.613,  13.850,  0.197,  2048.6, 'Italy wind_onshore cluster, 2049 MW across 59 plants (radius 124 km)'),
    ('IT' , 'wind_onshore_3'        , 'wind_onshore',  40.719,  16.291,  0.140,  1458.0, 'Italy wind_onshore cluster, 1458 MW across 54 plants (radius 132 km)'),
    ('IT' , 'wind_onshore_4'        , 'wind_onshore',  40.112,   8.886,  0.117,  1216.0, 'Italy wind_onshore cluster, 1216 MW across 29 plants (radius 108 km)'),
    ('IT' , 'wind_onshore_5'        , 'wind_onshore',  39.111,  16.844,  0.108,  1120.0, 'Italy wind_onshore cluster, 1120 MW across 35 plants (radius 184 km)'),
    ('IT' , 'wind_onshore_6'        , 'wind_onshore',  43.013,  11.770,  0.053,   554.2, 'Italy wind_onshore cluster, 554 MW across 23 plants (radius 326 km)'),
    ('IT' , 'wind_offshore_country' , 'wind_offshore',  40.485,  17.137,  1.000,    30.0, 'Italy wind_offshore cluster, 30 MW across 1 plants (radius 0 km)'),
    ('LT' , 'centroid'              , 'centroid'    ,  55.200,  23.850,  1.000,    None, 'Lithuania centroid'),
    ('LT' , 'solar_1'               , 'solar'       ,  55.374,  23.227,  0.530,   461.7, 'Lithuania solar cluster, 462 MW across 90 plants (radius 146 km)'),
    ('LT' , 'solar_2'               , 'solar'       ,  55.193,  25.372,  0.470,   409.9, 'Lithuania solar cluster, 410 MW across 46 plants (radius 121 km)'),
    ('LT' , 'wind_onshore_country'  , 'wind_onshore',  55.628,  22.658,  1.000,  1308.0, 'Lithuania wind_onshore cluster, 1308 MW across 27 plants (radius 144 km)'),
    ('LU' , 'centroid'              , 'centroid'    ,  49.800,   6.100,  1.000,    None, 'Luxembourg centroid'),
    ('LU' , 'solar_country'         , 'solar'       ,  49.654,   6.083,  1.000,   101.1, 'Luxembourg solar cluster, 101 MW across 45 plants (radius 46 km)'),
    ('LU' , 'wind_onshore_country'  , 'wind_onshore',  49.929,   6.049,  1.000,   131.6, 'Luxembourg wind_onshore cluster, 132 MW across 8 plants (radius 44 km)'),
    ('LV' , 'centroid'              , 'centroid'    ,  56.900,  24.550,  1.000,    None, 'Latvia centroid'),
    ('LV' , 'solar_country'         , 'solar'       ,  56.718,  24.086,  1.000,   585.3, 'Latvia solar cluster, 585 MW across 85 plants (radius 249 km)'),
    ('LV' , 'wind_onshore_country'  , 'wind_onshore',  57.191,  21.628,  1.000,   100.0, 'Latvia wind_onshore cluster, 100 MW across 3 plants (radius 76 km)'),
    ('MD' , 'centroid'              , 'centroid'    ,  47.000,  28.500,  1.000,    None, 'Moldova centroid'),
    ('MD' , 'solar_country'         , 'solar'       ,  46.913,  28.588,  1.000,   165.7, 'Moldova solar cluster, 166 MW across 47 plants (radius 182 km)'),
    ('ME' , 'centroid'              , 'centroid'    ,  42.500,  19.300,  1.000,    None, 'Montenegro centroid'),
    ('ME' , 'solar_country'         , 'solar'       ,  42.496,  19.200,  1.000,    16.9, 'Montenegro solar cluster, 17 MW across 4 plants (radius 24 km)'),
    ('ME' , 'wind_onshore_country'  , 'wind_onshore',  42.528,  19.138,  1.000,   118.0, 'Montenegro wind_onshore cluster, 118 MW across 2 plants (radius 60 km)'),
    ('MK' , 'centroid'              , 'centroid'    ,  41.500,  21.500,  1.000,    None, 'North Macedonia centroid'),
    ('MK' , 'solar_country'         , 'solar'       ,  41.597,  21.934,  1.000,   440.2, 'North Macedonia solar cluster, 440 MW across 91 plants (radius 101 km)'),
    ('MK' , 'wind_onshore_country'  , 'wind_onshore',  41.510,  22.301,  1.000,    73.0, 'North Macedonia wind_onshore cluster, 73 MW across 2 plants (radius 39 km)'),
    ('NL' , 'centroid'              , 'centroid'    ,  52.200,   5.300,  1.000,    None, 'Netherlands centroid'),
    ('NL' , 'solar_1'               , 'solar'       ,  52.860,   6.710,  0.382,  2634.3, 'Netherlands solar cluster, 2634 MW across 200 plants (radius 100 km)'),
    ('NL' , 'solar_2'               , 'solar'       ,  51.627,   5.711,  0.242,  1667.5, 'Netherlands solar cluster, 1668 MW across 247 plants (radius 90 km)'),
    ('NL' , 'solar_3'               , 'solar'       ,  52.621,   5.637,  0.214,  1477.9, 'Netherlands solar cluster, 1478 MW across 170 plants (radius 92 km)'),
    ('NL' , 'solar_4'               , 'solar'       ,  51.619,   4.288,  0.162,  1117.4, 'Netherlands solar cluster, 1117 MW across 131 plants (radius 98 km)'),
    ('NL' , 'wind_onshore_1'        , 'wind_onshore',  52.350,   5.633,  0.306,  1589.2, 'Netherlands wind_onshore cluster, 1589 MW across 55 plants (radius 121 km)'),
    ('NL' , 'wind_onshore_2'        , 'wind_onshore',  51.697,   4.187,  0.270,  1402.3, 'Netherlands wind_onshore cluster, 1402 MW across 61 plants (radius 77 km)'),
    ('NL' , 'wind_onshore_3'        , 'wind_onshore',  53.211,   6.890,  0.257,  1331.8, 'Netherlands wind_onshore cluster, 1332 MW across 32 plants (radius 86 km)'),
    ('NL' , 'wind_onshore_4'        , 'wind_onshore',  52.791,   4.805,  0.166,   862.8, 'Netherlands wind_onshore cluster, 863 MW across 15 plants (radius 63 km)'),
    ('NL' , 'wind_offshore_1'       , 'wind_offshore',  52.601,   4.242,  0.718,  4906.0, 'Netherlands wind_offshore cluster, 4906 MW across 17 plants (radius 59 km)'),
    ('NL' , 'wind_offshore_2'       , 'wind_offshore',  53.316,   5.681,  0.172,  1178.0, 'Netherlands wind_offshore cluster, 1178 MW across 3 plants (radius 68 km)'),
    ('NL' , 'wind_offshore_3'       , 'wind_offshore',  51.675,   3.035,  0.110,   752.0, 'Netherlands wind_offshore cluster, 752 MW across 2 plants (radius 5 km)'),
    ('NO' , 'centroid'              , 'centroid'    ,  64.550,  17.950,  1.000,    None, 'Norway centroid'),
    ('NO' , 'solar_country'         , 'solar'       ,  59.996,   9.639,  1.000,    35.8, 'Norway solar cluster, 36 MW across 10 plants (radius 374 km)'),
    ('NO' , 'wind_onshore_1'        , 'wind_onshore',  59.776,   5.875,  0.435,  2467.4, 'Norway wind_onshore cluster, 2467 MW across 28 plants (radius 322 km)'),
    ('NO' , 'wind_onshore_2'        , 'wind_onshore',  63.661,  10.679,  0.417,  2364.0, 'Norway wind_onshore cluster, 2364 MW across 22 plants (radius 471 km)'),
    ('NO' , 'wind_onshore_3'        , 'wind_onshore',  69.495,  20.479,  0.147,   834.0, 'Norway wind_onshore cluster, 834 MW across 12 plants (radius 373 km)'),
    ('NO' , 'wind_offshore_country' , 'wind_offshore',  60.522,   3.403,  1.000,   138.0, 'Norway wind_offshore cluster, 138 MW across 6 plants (radius 204 km)'),
    ('PL' , 'centroid'              , 'centroid'    ,  51.900,  19.150,  1.000,    None, 'Poland centroid'),
    ('PL' , 'solar_1'               , 'solar'       ,  52.145,  16.570,  0.090,   803.7, 'Poland solar cluster, 804 MW across 457 plants (radius 107 km)'),
    ('PL' , 'solar_2'               , 'solar'       ,  52.192,  18.549,  0.090,   800.9, 'Poland solar cluster, 801 MW across 315 plants (radius 106 km)'),
    ('PL' , 'solar_3'               , 'solar'       ,  52.986,  17.202,  0.087,   778.7, 'Poland solar cluster, 779 MW across 424 plants (radius 107 km)'),
    ('PL' , 'solar_4'               , 'solar'       ,  53.503,  15.300,  0.087,   778.1, 'Poland solar cluster, 778 MW across 353 plants (radius 104 km)'),
    ('PL' , 'solar_5'               , 'solar'       ,  52.542,  15.314,  0.083,   737.2, 'Poland solar cluster, 737 MW across 345 plants (radius 79 km)'),
    ('PL' , 'solar_6'               , 'solar'       ,  51.352,  15.564,  0.083,   736.6, 'Poland solar cluster, 737 MW across 329 plants (radius 82 km)'),
    ('PL' , 'solar_7'               , 'solar'       ,  53.358,  20.743,  0.066,   590.6, 'Poland solar cluster, 591 MW across 373 plants (radius 167 km)'),
    ('PL' , 'solar_8'               , 'solar'       ,  54.475,  17.607,  0.063,   563.3, 'Poland solar cluster, 563 MW across 154 plants (radius 96 km)'),
    ('PL' , 'solar_9'               , 'solar'       ,  50.823,  17.650,  0.063,   561.5, 'Poland solar cluster, 562 MW across 320 plants (radius 117 km)'),
    ('PL' , 'solar_10'              , 'solar'       ,  50.960,  19.661,  0.061,   544.3, 'Poland solar cluster, 544 MW across 387 plants (radius 150 km)'),
    ('PL' , 'solar_11'              , 'solar'       ,  50.457,  21.507,  0.054,   482.8, 'Poland solar cluster, 483 MW across 299 plants (radius 151 km)'),
    ('PL' , 'solar_12'              , 'solar'       ,  53.578,  19.264,  0.053,   477.3, 'Poland solar cluster, 477 MW across 303 plants (radius 119 km)'),
    ('PL' , 'solar_13'              , 'solar'       ,  53.465,  22.621,  0.044,   393.3, 'Poland solar cluster, 393 MW across 304 plants (radius 105 km)'),
    ('PL' , 'solar_14'              , 'solar'       ,  50.681,  23.093,  0.040,   353.3, 'Poland solar cluster, 353 MW across 172 plants (radius 154 km)'),
    ('PL' , 'solar_15'              , 'solar'       ,  52.113,  22.473,  0.036,   324.9, 'Poland solar cluster, 325 MW across 209 plants (radius 96 km)'),
    ('PL' , 'wind_onshore_1'        , 'wind_onshore',  54.401,  17.280,  0.148,  1329.0, 'Poland wind_onshore cluster, 1329 MW across 34 plants (radius 82 km)'),
    ('PL' , 'wind_onshore_2'        , 'wind_onshore',  54.101,  16.029,  0.140,  1254.0, 'Poland wind_onshore cluster, 1254 MW across 37 plants (radius 75 km)'),
    ('PL' , 'wind_onshore_3'        , 'wind_onshore',  52.777,  17.424,  0.129,  1158.1, 'Poland wind_onshore cluster, 1158 MW across 30 plants (radius 116 km)'),
    ('PL' , 'wind_onshore_4'        , 'wind_onshore',  53.297,  14.797,  0.111,   992.0, 'Poland wind_onshore cluster, 992 MW across 26 plants (radius 105 km)'),
    ('PL' , 'wind_onshore_5'        , 'wind_onshore',  53.778,  18.988,  0.102,   915.0, 'Poland wind_onshore cluster, 915 MW across 27 plants (radius 68 km)'),
    ('PL' , 'wind_onshore_6'        , 'wind_onshore',  50.642,  17.913,  0.081,   728.4, 'Poland wind_onshore cluster, 728 MW across 20 plants (radius 109 km)'),
    ('PL' , 'wind_onshore_7'        , 'wind_onshore',  52.001,  19.164,  0.075,   673.0, 'Poland wind_onshore cluster, 673 MW across 26 plants (radius 105 km)'),
    ('PL' , 'wind_onshore_8'        , 'wind_onshore',  53.281,  22.605,  0.059,   533.0, 'Poland wind_onshore cluster, 533 MW across 15 plants (radius 150 km)'),
    ('PL' , 'wind_onshore_9'        , 'wind_onshore',  53.216,  20.607,  0.056,   504.0, 'Poland wind_onshore cluster, 504 MW across 15 plants (radius 120 km)'),
    ('PL' , 'wind_onshore_10'       , 'wind_onshore',  51.569,  16.144,  0.056,   503.0, 'Poland wind_onshore cluster, 503 MW across 16 plants (radius 110 km)'),
    ('PL' , 'wind_onshore_11'       , 'wind_onshore',  50.567,  22.085,  0.042,   373.0, 'Poland wind_onshore cluster, 373 MW across 14 plants (radius 119 km)'),
    ('PT' , 'centroid'              , 'centroid'    ,  39.500,  -7.850,  1.000,    None, 'Portugal centroid'),
    ('PT' , 'solar_1'               , 'solar'       ,  38.388,  -8.362,  0.746,  2647.7, 'Portugal solar cluster, 2648 MW across 132 plants (radius 1701 km)'),
    ('PT' , 'solar_2'               , 'solar'       ,  40.528,  -7.750,  0.254,   903.2, 'Portugal solar cluster, 903 MW across 42 plants (radius 135 km)'),
    ('PT' , 'wind_onshore_1'        , 'wind_onshore',  41.249,  -7.804,  0.530,  2672.3, 'Portugal wind_onshore cluster, 2672 MW across 108 plants (radius 106 km)'),
    ('PT' , 'wind_onshore_2'        , 'wind_onshore',  39.925,  -8.237,  0.411,  2072.8, 'Portugal wind_onshore cluster, 2073 MW across 80 plants (radius 144 km)'),
    ('PT' , 'wind_onshore_3'        , 'wind_onshore',  37.147,  -8.648,  0.060,   301.0, 'Portugal wind_onshore cluster, 301 MW across 15 plants (radius 909 km)'),
    ('PT' , 'wind_offshore_country' , 'wind_offshore',  41.687,  -9.057,  1.000,    25.0, 'Portugal wind_offshore cluster, 25 MW across 1 plants (radius 0 km)'),
    ('RO' , 'centroid'              , 'centroid'    ,  45.950,  25.000,  1.000,    None, 'Romania centroid'),
    ('RO' , 'solar_1'               , 'solar'       ,  44.609,  25.747,  0.380,  1371.3, 'Romania solar cluster, 1371 MW across 152 plants (radius 139 km)'),
    ('RO' , 'solar_2'               , 'solar'       ,  46.753,  22.078,  0.203,   731.6, 'Romania solar cluster, 732 MW across 98 plants (radius 165 km)'),
    ('RO' , 'solar_3'               , 'solar'       ,  46.346,  24.470,  0.199,   719.2, 'Romania solar cluster, 719 MW across 89 plants (radius 259 km)'),
    ('RO' , 'solar_4'               , 'solar'       ,  44.376,  23.731,  0.130,   469.9, 'Romania solar cluster, 470 MW across 71 plants (radius 118 km)'),
    ('RO' , 'solar_5'               , 'solar'       ,  45.095,  27.405,  0.089,   321.0, 'Romania solar cluster, 321 MW across 65 plants (radius 240 km)'),
    ('RO' , 'wind_onshore_1'        , 'wind_onshore',  44.608,  28.375,  0.461,  2528.0, 'Romania wind_onshore cluster, 2528 MW across 42 plants (radius 96 km)'),
    ('RO' , 'wind_onshore_2'        , 'wind_onshore',  45.932,  24.424,  0.435,  2388.0, 'Romania wind_onshore cluster, 2388 MW across 26 plants (radius 254 km)'),
    ('RO' , 'wind_onshore_3'        , 'wind_onshore',  46.738,  27.302,  0.104,   568.0, 'Romania wind_onshore cluster, 568 MW across 9 plants (radius 150 km)'),
    ('RS' , 'centroid'              , 'centroid'    ,  44.000,  21.000,  1.000,    None, 'Serbia centroid'),
    ('RS' , 'solar_country'         , 'solar'       ,  44.625,  20.620,  1.000,   199.2, 'Serbia solar cluster, 199 MW across 38 plants (radius 248 km)'),
    ('RS' , 'wind_onshore_country'  , 'wind_onshore',  44.956,  20.971,  1.000,   604.1, 'Serbia wind_onshore cluster, 604 MW across 8 plants (radius 133 km)'),
    ('SE' , 'centroid'              , 'centroid'    ,  62.200,  17.600,  1.000,    None, 'Sweden centroid'),
    ('SE' , 'solar_country'         , 'solar'       ,  57.989,  15.329,  1.000,   663.1, 'Sweden solar cluster, 663 MW across 100 plants (radius 872 km)'),
    ('SE' , 'wind_onshore_1'        , 'wind_onshore',  65.172,  20.732,  0.166,  2722.8, 'Sweden wind_onshore cluster, 2723 MW across 21 plants (radius 175 km)'),
    ('SE' , 'wind_onshore_2'        , 'wind_onshore',  62.899,  17.068,  0.111,  1814.5, 'Sweden wind_onshore cluster, 1814 MW across 20 plants (radius 126 km)'),
    ('SE' , 'wind_onshore_3'        , 'wind_onshore',  64.224,  18.104,  0.109,  1790.0, 'Sweden wind_onshore cluster, 1790 MW across 22 plants (radius 194 km)'),
    ('SE' , 'wind_onshore_4'        , 'wind_onshore',  63.586,  15.606,  0.101,  1660.4, 'Sweden wind_onshore cluster, 1660 MW across 18 plants (radius 117 km)'),
    ('SE' , 'wind_onshore_5'        , 'wind_onshore',  62.294,  15.583,  0.091,  1489.6, 'Sweden wind_onshore cluster, 1490 MW across 16 plants (radius 80 km)'),
    ('SE' , 'wind_onshore_6'        , 'wind_onshore',  60.640,  16.336,  0.086,  1417.0, 'Sweden wind_onshore cluster, 1417 MW across 23 plants (radius 161 km)'),
    ('SE' , 'wind_onshore_7'        , 'wind_onshore',  57.214,  15.074,  0.073,  1189.8, 'Sweden wind_onshore cluster, 1190 MW across 23 plants (radius 112 km)'),
    ('SE' , 'wind_onshore_8'        , 'wind_onshore',  58.667,  14.399,  0.056,   924.4, 'Sweden wind_onshore cluster, 924 MW across 29 plants (radius 162 km)'),
    ('SE' , 'wind_onshore_9'        , 'wind_onshore',  58.961,  12.094,  0.053,   862.1, 'Sweden wind_onshore cluster, 862 MW across 27 plants (radius 110 km)'),
    ('SE' , 'wind_onshore_10'       , 'wind_onshore',  61.574,  14.011,  0.051,   842.0, 'Sweden wind_onshore cluster, 842 MW across 15 plants (radius 144 km)'),
    ('SE' , 'wind_onshore_11'       , 'wind_onshore',  56.729,  13.055,  0.042,   688.4, 'Sweden wind_onshore cluster, 688 MW across 35 plants (radius 151 km)'),
    ('SE' , 'wind_onshore_12'       , 'wind_onshore',  57.159,  16.586,  0.039,   642.8, 'Sweden wind_onshore cluster, 643 MW across 23 plants (radius 154 km)'),
    ('SE' , 'wind_onshore_13'       , 'wind_onshore',  67.178,  22.040,  0.021,   342.0, 'Sweden wind_onshore cluster, 342 MW across 5 plants (radius 96 km)'),
    ('SE' , 'wind_offshore_country' , 'wind_offshore',  56.494,  13.963,  1.000,   188.0, 'Sweden wind_offshore cluster, 188 MW across 3 plants (radius 309 km)'),
    ('SI' , 'centroid'              , 'centroid'    ,  46.150,  15.000,  1.000,    None, 'Slovenia centroid'),
    ('SI' , 'solar_country'         , 'solar'       ,  46.128,  15.107,  1.000,    93.6, 'Slovenia solar cluster, 94 MW across 39 plants (radius 115 km)'),
    ('SK' , 'centroid'              , 'centroid'    ,  48.650,  19.700,  1.000,    None, 'Slovakia centroid'),
    ('SK' , 'solar_1'               , 'solar'       ,  48.605,  20.615,  0.536,   477.3, 'Slovakia solar cluster, 477 MW across 119 plants (radius 117 km)'),
    ('SK' , 'solar_2'               , 'solar'       ,  48.319,  18.393,  0.464,   413.1, 'Slovakia solar cluster, 413 MW across 116 plants (radius 114 km)'),
    ('UA' , 'centroid'              , 'centroid'    ,  49.000,  32.000,  1.000,    None, 'Ukraine centroid'),
    ('UA' , 'solar_1'               , 'solar'       ,  47.713,  32.006,  0.231,  1314.7, 'Ukraine solar cluster, 1315 MW across 90 plants (radius 164 km)'),
    ('UA' , 'solar_2'               , 'solar'       ,  47.891,  34.847,  0.230,  1305.6, 'Ukraine solar cluster, 1306 MW across 96 plants (radius 225 km)'),
    ('UA' , 'solar_3'               , 'solar'       ,  49.306,  27.724,  0.150,   854.1, 'Ukraine solar cluster, 854 MW across 107 plants (radius 205 km)'),
    ('UA' , 'solar_4'               , 'solar'       ,  46.015,  33.537,  0.127,   720.2, 'Ukraine solar cluster, 720 MW across 56 plants (radius 138 km)'),
    ('UA' , 'solar_5'               , 'solar'       ,  48.941,  23.981,  0.117,   668.5, 'Ukraine solar cluster, 668 MW across 100 plants (radius 157 km)'),
    ('UA' , 'solar_6'               , 'solar'       ,  46.160,  29.829,  0.075,   426.8, 'Ukraine solar cluster, 427 MW across 33 plants (radius 145 km)'),
    ('UA' , 'solar_7'               , 'solar'       ,  50.239,  31.069,  0.070,   397.8, 'Ukraine solar cluster, 398 MW across 42 plants (radius 226 km)'),
    ('UA' , 'wind_onshore_country'  , 'wind_onshore',  47.050,  32.352,  1.000,   560.4, 'Ukraine wind_onshore cluster, 560 MW across 17 plants (radius 743 km)'),
]
# === LOCATIONS-AUTOGEN-END ===


# ---------------------------------------------------------------------------
# Hand-seeded locations (NOT regenerated by build_weather_locations.py)
# ---------------------------------------------------------------------------
# Rows below come from sources outside GEM (Global Energy Monitor) plant data.
# The autogen rewriter only touches text between the LOCATIONS-AUTOGEN-START
# / -END markers above, so this block is preserved across rebuilds.
#
# Belgium solar zip-derived zones (`solar_zip_v1`):
#   Source: helioforge `docs/installed_capacity_per_zip_code.xls`
#           (Belgian residential + commercial PV per zip code, 2026-03 snapshot;
#            sum 8,167 MW across 358 active zips — full national fleet).
#   Method: capacity-weighted k-means with K=10 on (lat, lon) weighted by
#           installed_capacity per zip.
#   Why distinct zone_type: keeps existing consumers that filter on
#           zone_type='solar' (heliocast prod, dashboards) unaffected. The two
#           GEM-derived BE solar zones above (solar_1, solar_2; ~905 MW total)
#           remain in place.
#   Audit + cluster JSON: helioforge `evaluation/zone_audit/README.md` and
#           `evaluation/zip_zones_clusters.json`.

_EXTRA_LOCATIONS: list[tuple] = [
    # country, zone_id, zone_type, lat, lon, weight, capacity_mw, description
    ('BE' , 'solar_zip_01'          , 'solar_zip_v1',  50.973,   4.266,  0.175,  1431.4, 'Belgium solar_zip_v1 cluster (Brussels NE / Mechelen), 1431 MW across 46 zips'),
    ('BE' , 'solar_zip_02'          , 'solar_zip_v1',  51.159,   4.558,  0.146,  1196.2, 'Belgium solar_zip_v1 cluster (Antwerp metro), 1196 MW across 36 zips'),
    ('BE' , 'solar_zip_03'          , 'solar_zip_v1',  50.688,   5.565,  0.141,  1154.1, 'Belgium solar_zip_v1 cluster (Liège region), 1154 MW across 64 zips'),
    ('BE' , 'solar_zip_04'          , 'solar_zip_v1',  51.035,   3.715,  0.120,   983.6, 'Belgium solar_zip_v1 cluster (Ghent / E.Flanders), 984 MW across 29 zips'),
    ('BE' , 'solar_zip_05'          , 'solar_zip_v1',  51.167,   5.053,  0.103,   842.4, 'Belgium solar_zip_v1 cluster (Limburg, Geel/Hasselt), 842 MW across 25 zips'),
    ('BE' , 'solar_zip_06'          , 'solar_zip_v1',  50.871,   3.316,  0.096,   787.7, 'Belgium solar_zip_v1 cluster (Kortrijk / W.Flanders), 788 MW across 28 zips'),
    ('BE' , 'solar_zip_07'          , 'solar_zip_v1',  51.061,   3.013,  0.093,   758.0, 'Belgium solar_zip_v1 cluster (Bruges / coastal), 758 MW across 26 zips'),
    ('BE' , 'solar_zip_08'          , 'solar_zip_v1',  50.498,   4.597,  0.059,   479.9, 'Belgium solar_zip_v1 cluster (Charleroi / Namur), 480 MW across 53 zips'),
    ('BE' , 'solar_zip_09'          , 'solar_zip_v1',  50.605,   3.968,  0.049,   400.7, 'Belgium solar_zip_v1 cluster (Mons / Hainaut), 401 MW across 30 zips'),
    ('BE' , 'solar_zip_10'          , 'solar_zip_v1',  49.902,   5.502,  0.016,   133.2, 'Belgium solar_zip_v1 cluster (Luxembourg / Bastogne), 133 MW across 21 zips'),

    # ------------------------------------------------------------------
    # v035 grid cells — top-25 cells by v030 gain importance (SW-Belgium
    # concentration). Added 2026-05-15 to feed heliocast's v035 daily
    # Predico submission (production/scheduler.py). Each cell is a 0.1°
    # square; coords here are the cell centroids.
    # Weights are total_gain_v030 / sum(gain) — informational; the v035
    # model uses cells independently (no aggregation).
    # Source: heliocast/production/grid_cells.json.
    # ------------------------------------------------------------------
    ('BE' , 'g044'                  , 'solar_grid_v035',  50.450,   3.750, 0.1161,   12.20, 'Belgium solar_grid_v035 cell  1/25 (lat 50.45, lon 3.75, 2 zips, 12.2 MW capacity, gain 67300)'),
    ('BE' , 'g103'                  , 'solar_grid_v035',  50.750,   3.850, 0.0778,   22.35, 'Belgium solar_grid_v035 cell  2/25 (lat 50.75, lon 3.85, 1 zips, 22.4 MW capacity, gain 45089)'),
    ('BE' , 'g031'                  , 'solar_grid_v035',  50.350,   3.850, 0.0706,    8.93, 'Belgium solar_grid_v035 cell  3/25 (lat 50.35, lon 3.85, 1 zips, 8.9 MW capacity, gain 40930)'),
    ('BE' , 'g046'                  , 'solar_grid_v035',  50.450,   3.950, 0.0652,   64.15, 'Belgium solar_grid_v035 cell  4/25 (lat 50.45, lon 3.95, 4 zips, 64.2 MW capacity, gain 37773)'),
    ('BE' , 'g117'                  , 'solar_grid_v035',  50.850,   2.850, 0.0543,  101.08, 'Belgium solar_grid_v035 cell  5/25 (lat 50.85, lon 2.85, 1 zips, 101.1 MW capacity, gain 31470)'),
    ('BE' , 'g066'                  , 'solar_grid_v035',  50.550,   3.650, 0.0539,   18.05, 'Belgium solar_grid_v035 cell  6/25 (lat 50.55, lon 3.65, 1 zips, 18.1 MW capacity, gain 31245)'),
    ('BE' , 'g045'                  , 'solar_grid_v035',  50.450,   3.850, 0.0445,   18.74, 'Belgium solar_grid_v035 cell  7/25 (lat 50.45, lon 3.85, 3 zips, 18.7 MW capacity, gain 25806)'),
    ('BE' , 'g002'                  , 'solar_grid_v035',  49.550,   5.850, 0.0419,   11.52, 'Belgium solar_grid_v035 cell  8/25 (lat 49.55, lon 5.85, 1 zips, 11.5 MW capacity, gain 24290)'),
    ('BE' , 'g179'                  , 'solar_grid_v035',  51.050,   5.750, 0.0415,   31.01, 'Belgium solar_grid_v035 cell  9/25 (lat 51.05, lon 5.75, 2 zips, 31.0 MW capacity, gain 24054)'),
    ('BE' , 'g102'                  , 'solar_grid_v035',  50.750,   3.650, 0.0402,   21.98, 'Belgium solar_grid_v035 cell 10/25 (lat 50.75, lon 3.65, 1 zips, 22.0 MW capacity, gain 23294)'),
    ('BE' , 'g208'                  , 'solar_grid_v035',  51.250,   3.150, 0.0390,   12.23, 'Belgium solar_grid_v035 cell 11/25 (lat 51.25, lon 3.15, 1 zips, 12.2 MW capacity, gain 22600)'),
    ('BE' , 'g099'                  , 'solar_grid_v035',  50.750,   2.950, 0.0366,   17.11, 'Belgium solar_grid_v035 cell 12/25 (lat 50.75, lon 2.95, 2 zips, 17.1 MW capacity, gain 21188)'),
    ('BE' , 'g141'                  , 'solar_grid_v035',  50.950,   3.350, 0.0330,  119.97, 'Belgium solar_grid_v035 cell 13/25 (lat 50.95, lon 3.35, 3 zips, 120.0 MW capacity, gain 19152)'),
    ('BE' , 'g098'                  , 'solar_grid_v035',  50.650,   6.150, 0.0289,   34.42, 'Belgium solar_grid_v035 cell 14/25 (lat 50.65, lon 6.15, 1 zips, 34.4 MW capacity, gain 16744)'),
    ('BE' , 'g223'                  , 'solar_grid_v035',  51.350,   3.350, 0.0279,    3.70, 'Belgium solar_grid_v035 cell 15/25 (lat 51.35, lon 3.35, 1 zips, 3.7 MW capacity, gain 16149)'),
    ('BE' , 'g001'                  , 'solar_grid_v035',  49.550,   5.550, 0.0272,    4.10, 'Belgium solar_grid_v035 cell 16/25 (lat 49.55, lon 5.55, 1 zips, 4.1 MW capacity, gain 15778)'),
    ('BE' , 'g047'                  , 'solar_grid_v035',  50.450,   4.050, 0.0243,    9.63, 'Belgium solar_grid_v035 cell 17/25 (lat 50.45, lon 4.05, 2 zips, 9.6 MW capacity, gain 14099)'),
    ('BE' , 'g221'                  , 'solar_grid_v035',  51.350,   3.150, 0.0232,   25.00, 'Belgium solar_grid_v035 cell 18/25 (lat 51.35, lon 3.15, 1 zips, 25.0 MW capacity, gain 13449)'),
    ('BE' , 'g205'                  , 'solar_grid_v035',  51.150,   5.650, 0.0232,   14.59, 'Belgium solar_grid_v035 cell 19/25 (lat 51.15, lon 5.65, 1 zips, 14.6 MW capacity, gain 13445)'),
    ('BE' , 'g157'                  , 'solar_grid_v035',  50.950,   5.650, 0.0231,    6.42, 'Belgium solar_grid_v035 cell 20/25 (lat 50.95, lon 5.65, 1 zips, 6.4 MW capacity, gain 13396)'),
    ('BE' , 'g115'                  , 'solar_grid_v035',  50.750,   5.750, 0.0227,   35.18, 'Belgium solar_grid_v035 cell 21/25 (lat 50.75, lon 5.75, 2 zips, 35.2 MW capacity, gain 13151)'),
    ('BE' , 'g006'                  , 'solar_grid_v035',  49.650,   5.750, 0.0218,   12.24, 'Belgium solar_grid_v035 cell 22/25 (lat 49.65, lon 5.75, 1 zips, 12.2 MW capacity, gain 12651)'),
    ('BE' , 'g116'                  , 'solar_grid_v035',  50.750,   5.950, 0.0217,    9.00, 'Belgium solar_grid_v035 cell 23/25 (lat 50.75, lon 5.95, 1 zips, 9.0 MW capacity, gain 12554)'),
    ('BE' , 'g137'                  , 'solar_grid_v035',  50.950,   2.750, 0.0208,   28.11, 'Belgium solar_grid_v035 cell 24/25 (lat 50.95, lon 2.75, 1 zips, 28.1 MW capacity, gain 12063)'),
    ('BE' , 'g043'                  , 'solar_grid_v035',  50.350,   6.150, 0.0205,    4.78, 'Belgium solar_grid_v035 cell 25/25 (lat 50.35, lon 6.15, 1 zips, 4.8 MW capacity, gain 11908)'),
]

LOCATIONS = LOCATIONS + _EXTRA_LOCATIONS


# ---------------------------------------------------------------------------
# Source dimension — provider × model × lead-time combinations we'll use
# ---------------------------------------------------------------------------

OPEN_METEO_SOURCES = [
    # provider,                     model_id,         lead_time_hours, description
    ("open_meteo_archive",          "era5",                        0, "ERA5 reanalysis (historical truth)"),
    # Real-time forecast API (hourly ingest — serves heliocast's inference).
    ("open_meteo_forecast",         "best_match",                 -1, "Real-time forecast API, Open-Meteo best_match"),
    ("open_meteo_forecast",         "ecmwf_ifs025",               -1, "Real-time forecast API, ECMWF IFS 0.25°"),
    ("open_meteo_forecast",         "icon_seamless",              -1, "Real-time forecast API, DWD ICON-EU 11 km"),
    ("open_meteo_forecast",         "gfs_seamless",               -1, "Real-time forecast API, NOAA GFS 0.11°"),
    ("open_meteo_forecast",         "knmi_harmonie_arome_europe", -1, "Real-time forecast API, KNMI HARMONIE-AROME Europe 5.5 km"),
    ("open_meteo_forecast",         "meteofrance_arome_france",   -1, "Real-time forecast API, Météo-France AROME France 1.3 km"),
    ("open_meteo_forecast",         "icon_d2",                    -1, "Real-time forecast API, DWD ICON-D2 2.2 km"),
    # Previous Runs archive (3×/day ingest — replay + backtest substrate).
    # Each NWP model registered at day1 (24h), day2 (48h), day3 (72h) lead.
    # Short-range models (AROME, ICON-D2) return NULL for day3 — harmless;
    # keeps the lead dimension uniform across sources.
    ("open_meteo_previous_runs",    "best_match",                 24, "Previous Runs API, day1 lead"),
    ("open_meteo_previous_runs",    "best_match",                 48, "Previous Runs API, day2 lead"),
    ("open_meteo_previous_runs",    "best_match",                 72, "Previous Runs API, day3 lead"),
    ("open_meteo_previous_runs",    "ecmwf_ifs025",               24, "ECMWF IFS 0.25°, day1 lead"),
    ("open_meteo_previous_runs",    "ecmwf_ifs025",               48, "ECMWF IFS 0.25°, day2 lead"),
    ("open_meteo_previous_runs",    "ecmwf_ifs025",               72, "ECMWF IFS 0.25°, day3 lead"),
    ("open_meteo_previous_runs",    "gfs_seamless",               24, "NOAA GFS, day1 lead"),
    ("open_meteo_previous_runs",    "gfs_seamless",               48, "NOAA GFS, day2 lead"),
    ("open_meteo_previous_runs",    "gfs_seamless",               72, "NOAA GFS, day3 lead"),
    ("open_meteo_previous_runs",    "icon_seamless",              24, "DWD ICON-EU, day1 lead"),
    ("open_meteo_previous_runs",    "icon_seamless",              48, "DWD ICON-EU, day2 lead"),
    ("open_meteo_previous_runs",    "icon_seamless",              72, "DWD ICON-EU, day3 lead"),
    ("open_meteo_previous_runs",    "knmi_harmonie_arome_europe", 24, "KNMI HARMONIE-AROME, day1 lead"),
    ("open_meteo_previous_runs",    "knmi_harmonie_arome_europe", 48, "KNMI HARMONIE-AROME, day2 lead (may be NULL — short-range)"),
    ("open_meteo_previous_runs",    "knmi_harmonie_arome_europe", 72, "KNMI HARMONIE-AROME, day3 lead (may be NULL — short-range)"),
    ("open_meteo_previous_runs",    "meteofrance_arome_france",   24, "Météo-France AROME, day1 lead"),
    ("open_meteo_previous_runs",    "meteofrance_arome_france",   48, "Météo-France AROME, day2 lead (may be NULL — short-range)"),
    ("open_meteo_previous_runs",    "meteofrance_arome_france",   72, "Météo-France AROME, day3 lead (may be NULL — short-range)"),
    ("open_meteo_previous_runs",    "icon_d2",                    24, "DWD ICON-D2, day1 lead"),
    ("open_meteo_previous_runs",    "icon_d2",                    48, "DWD ICON-D2, day2 lead (may be NULL — short-range)"),
    ("open_meteo_previous_runs",    "icon_d2",                    72, "DWD ICON-D2, day3 lead (may be NULL — short-range)"),
]


# ---------------------------------------------------------------------------
# DDL — CREATE TABLE IF NOT EXISTS statements
# ---------------------------------------------------------------------------

SCHEMA_LOCATION = """
CREATE TABLE IF NOT EXISTS weather_location (
    location_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    country_code  TEXT    NOT NULL,
    zone_id       TEXT    NOT NULL,
    zone_type     TEXT,
    lat           REAL    NOT NULL,
    lon           REAL    NOT NULL,
    weight        REAL,
    capacity_mw   REAL,
    description   TEXT,
    created_at    TEXT    DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(country_code, zone_id)
)
"""

SCHEMA_SOURCE = """
CREATE TABLE IF NOT EXISTS weather_source (
    source_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    provider         TEXT    NOT NULL,
    model_id         TEXT    NOT NULL,
    lead_time_hours  INTEGER NOT NULL,
    description      TEXT,
    created_at       TEXT    DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider, model_id, lead_time_hours)
)
"""

# weather_observation columns are generated from WEATHER_VARIABLE_COLUMNS.
_OBSERVATION_VAR_DDL = ",\n    ".join(f"{c} REAL" for c in WEATHER_VARIABLE_COLUMNS)

SCHEMA_OBSERVATION = f"""
CREATE TABLE IF NOT EXISTS weather_observation (
    source_id          INTEGER NOT NULL REFERENCES weather_source(source_id),
    location_id        INTEGER NOT NULL REFERENCES weather_location(location_id),
    valid_at           TEXT    NOT NULL,
    forecast_run_time  TEXT,
    fetched_at         TEXT    NOT NULL,
    {_OBSERVATION_VAR_DDL},
    PRIMARY KEY (source_id, location_id, valid_at, fetched_at)
)
"""

SCHEMA_INDEXES = [
    """
    CREATE INDEX IF NOT EXISTS idx_wx_replay
    ON weather_observation(location_id, valid_at, source_id, fetched_at DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_wx_source_latest
    ON weather_observation(source_id, location_id, fetched_at DESC, valid_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_weather_location_zone_type
    ON weather_location(zone_type)
    """,
]


ALL_SCHEMA_SQL = [SCHEMA_LOCATION, SCHEMA_SOURCE, SCHEMA_OBSERVATION, *SCHEMA_INDEXES]


__all__ = [
    "WEATHER_VARIABLE_COLUMNS",
    "OPENMETEO_TO_DB",
    "LOCATIONS",
    "OPEN_METEO_SOURCES",
    "SCHEMA_LOCATION",
    "SCHEMA_SOURCE",
    "SCHEMA_OBSERVATION",
    "SCHEMA_INDEXES",
    "ALL_SCHEMA_SQL",
]
